# -*- coding: utf-8 -*-
"""python-excel-kadai2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-2Qw8mv9EKAMd42vNTIXxIsZPzdZkN5
"""

import pandas as pd

# 社員ごとの売上データを作成
data = {
    "日付": ["2023-05-17", "2023-05-18", "2023-05-19", "2023-05-20", "2023-05-21"],
    "社員名": ["山田", "佐藤", "鈴木", "田中", "高橋"],
    "売上": [100, 200, 150, 300, 250],
    "部門": ["メーカー", "代理店", "メーカー", "商社", "代理店"]
}

df = pd.DataFrame(data)

# 「平均売上」列を作成
df["平均売上"] = df["売上"].mean()

# 「業績ランク」列を作成
def performance(earn):
    rank = ""
    mean = df["売上"].mean()
    if earn >= mean + 50:
        rank = "A"
    elif earn == mean:
        rank = "B"
    else:
        rank = "C"
    return rank

df["業績ランク"] = df["売上"].apply(performance)

# 「業績.xlsx」を書き出し
writer = pd.ExcelWriter("業績.xlsx")

df.to_excel(writer, sheet_name="Sheet1", index=False)

writer.close()

