# -*- coding: utf-8 -*-
"""python-excel-kadai1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_PYcHHlQViC1t4OffPyEdMl_cfOQWpfz
"""

import openpyxl
from datetime import datetime

workbook = openpyxl.Workbook()
worksheet = workbook.active

today = datetime.today()
#print(today.strftime("%Y%m%d"))

#固定情報の入力
worksheet["B2"] = "請求書"
worksheet["F4"] = "No."
worksheet["G4"] = "0001"
worksheet["F5"] = "日付"
worksheet["G5"] = today.strftime('%Y/%m/%d')

fix_data = ["株式会社ABC",
            "〒101-0022 東京都千代田区神田練塀町300",
            "TEL:03-1234-5678 FAX:03-1234-5678",
            "担当者名:鈴木一郎 様"
]

row = 4

for data in fix_data:
    worksheet[f"B{row}"] = data
    row = row + 1

#商品情報の入力
product_data = [
    ["", "商品名", "数量", "単価", "金額"],
    ["", "商品A", 2, 10000, 20000],
    ["", "商品B", 1, 15000, 15000]
]

subtotal_cost = 0

for product in product_data:
    worksheet.append(product)

    if product[4] != "金額":
        subtotal_cost = subtotal_cost + product[4]

#print(total_cost)

#商品情報と固定情報の間に空行を2行挿入
worksheet.insert_rows(8, 2)

#合計金額をE列の最終行の下に入力
last_row = worksheet.max_row +1
#print(last_row)

worksheet[f"E{last_row}"] = subtotal_cost

#合計(subtotal_cost)、消費税(tax)、税込合計(total_cost)を入力する

tax = subtotal_cost * 0.1
total_cost = subtotal_cost + tax

target_row = worksheet.max_row + 2

cost_data = [
    ["合計", subtotal_cost],
    ["消費税", tax],
    ["税込合計", total_cost]
]

for data in cost_data:
    worksheet[f"B{target_row}"] = data[0]
    worksheet[f"E{target_row}"] = data[1]
    target_row = target_row + 1

#列の幅を11に変更する
target_col = worksheet.max_column
width = 11

for col in range(1,target_col+1):
    worksheet.column_dimensions[openpyxl.utils.get_column_letter(col)].width = width

#ファイル出力
workbook.save(f"請求書_{today.strftime('%Y%m%d')}.xlsx")

