# -*- coding: utf-8 -*-
"""python-excel-kadai3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJoYezYk1fpw_u5b4EygToYGRqmLSvpw
"""

import openpyxl
import pandas as pd
from openpyxl.styles import PatternFill

# 2022‗年間売上表の読み込み
df1 = pd.read_excel("2022_年間売上表.xlsx", sheet_name = "Sheet1")

# 2023‗年間売上表の読み込み
df2 = pd.read_excel("2023_年間売上表.xlsx", sheet_name = "Sheet1")

# 2022年と2023年の売上表を結合する
df_concat = pd.concat([df1, df2])

# 「商品」「売上年」ごとにグループ化し、合計金額に集約
result = df_concat.groupby(["商品", "売上年"], as_index=False).sum()

#print(result)

# Excelブックを作成する
result.to_excel("売上集計表.xlsx", sheet_name = "合計金額", index=False)

# Excelファイルの読み込み
wb = openpyxl.load_workbook("売上集計表.xlsx")
ws = wb.active

# 色の設定
fill = PatternFill(patternType="solid", fgColor="F2F2F2")

#ws["A1"].fill = fill

for cell in ws["A1":"C1"]:
#    print(cell)
    for i in cell:
        i.fill = fill

# 列幅の調整
for col in ["A", "B", "C"]:
    ws.column_dimensions[col].width = 18


wb.save("売上集計表.xlsx")

